### ISSUE TITLE
시간표가 날짜 인식을 못함

### ISSUE THREAD

**Issue by JeongAnNa** [iseolin76/GoGo#16]
내일도 모레도 다음주 목요일도 모두 6월 28일이래요 문제가 많습니다 고쳐주세요 디벨로퍼

**Comment by JeongAnNa** [comment]
<img width="484" alt="스크린샷 2021-06-28 오전 11 11 41" src="https://user-images.githubusercontent.com/73638227/123569622-9e758180-d801-11eb-90f8-7aa3016bc7c1.png">

**Comment by iseolin76** [comment]
해당 사항은 날짜를 잘 못 카운트하여 발생한 일로,
수정완료되었습니다.
만약 안 고쳐졌다면 다시 이슈를 열어주세요 :)
