### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by jjmin321** [iseolin76/GoGo#26]
/api/requestapi.go : 먼저 resp, data에 대한 리소스 해제를 해주세요. 그리고 프로덕션 환경에서 실행되는 코드는 패닉을 반드시 피해야 합니다. 에러가 발생할 경우, 함수는 에러를 리턴하고 호출자가 오류 처리 방법을 결정할 수 있도록 해야 합니다. Recover을 같이 사용하거나 Fatal을 사용해주세요

/main.go : 리소스 해제는 즉시 defer로 해야 합니다. defer dg.close()를 dg 객체 생성 후에 바로 추가해주세요. 

/main.go : 채널을 처음부터 미리 만들어두고 블로킹하는게 보기에 더 좋아보여요.

**Comment by iseolin76** [comment]
혹시 data에 대한 리소스 해제 방법에 대해 여쭤볼 수 있을까요?

다른 부분은 다 처리하였는데 data에 대한 리소스 해제를 잘 모르겠습니다.

**Comment by jjmin321** [comment]
data는 리소스가 아니네요 잘못 본 것 같아요, 👍
